version: "3.8"

services:
  files:
    container_name: files_storage
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    restart: always
    env_file:
      - .env
    volumes:
      - files_storage:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - backend

  db:
    container_name: database
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - pg_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  app:
    container_name: application
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - files
    networks:
      - backend

  nginx:
    image: nginx:1.23.3
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pg_db:
  files_storage:
