version: "3.1"

services:
  files:
    container_name: files_storage
    command: server /data --console-address ":9001"
    image: minio/minio:latest
    volumes:
      - files_storage:/data
    restart: always
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - backend

  db:
    container_name: database
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - pg_db:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - backend

  app:
    container_name: application
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    depends_on:
      - db
      - files
    networks:
      - backend

  nginx:
    image: nginx:1.23.3
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cert.pem:/etc/cert.pem
      - ./nginx/key.pem:/etc/key.pem
    networks:
      - backend

  certbot:
    container_name: certbot
    ports:
      - "6000:80"
    env_file:
      - .env
    volumes:
      - ./nginx/:etc/nginx
    build:
      context: ./certbot
      dockerfile: Dockerfile
      args:
        DOMAIN_URL: ${DOMAIN_URL}
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pg_db:
  files_storage: