spring:
  application:
    name: CloudStorage
  datasource:
    driver-class: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB

server:
  port: 8000

jwt:
  lifetime: 1d
  issuer: localhost:8000
  refreshLifetime: 30d

minio:
  avatarBucket: avatars
  filesBucket: users

file:
  storage:
    extensions: .jpg,.png,.pdf,.txt,.jpeg