package com.myrr.CloudStorage.domain.enums;

public enum ApiErrorCode {
    USER_NOT_FOUND,
    INVALID_DATA,
    INTERNAL_ERROR,
    USERNAME_OR_EMAIL_ALREADY_EXISTS,
    INVALID_REFRESH_TOKEN,
    DIRECTORY_NOT_FOUND,
    FILE_CONFLICT,
    INVALID_PARENT,
    FILE_NOT_FOUND,
    NO_FILES
}
